apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-container
          image: madsens/app-with-argocd:aa4676dff7389eb1c0e94f52ac6ac72c42f69778
          ports:
            - containerPort: 8080